<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv [
    <!ELEMENT cv (nombre, idiomas, lenguas)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT idiomas (idioma*)>
    <!ELEMENT idioma (#PCDATA)>
    <!ELEMENT lenguas (lengua*)>
    <!ELEMENT lengua (#PCDATA)>
    <!ATTLIST lengua identificador ID #REQUIRED>
    <!ATTLIST idioma nivel (bajo|medio|alto) "medio">
    <!ATTLIST idioma codigoPais IDREF #REQUIRED>
]>

<cv>
    <nombre>Desmond Miles</nombre>
    <idiomas>
        <idioma codigoPais="fr" nivel="bajo">Francés</idioma>
        <idioma codigoPais="en" >Inglés</idioma>
        <idioma codigoPais="it" >Italiano</idioma>
    </idiomas>
    <lenguas>
        <lengua identificador="fr">Francés</lengua>
        <lengua identificador="en">Francés</lengua>
        <lengua identificador="it">Francés</lengua>
    </lenguas>
</cv>